participants = ['Ale Delgado',
                'Barbara Salazar',
                'Bella Delgado',
                'El Tito',
                'Fer Elizondo',
                'German Jr Martinez',
                'German Sr Martinez',
                'Hugo 2nd (Tio)',
                'Hugo 3rd (Huguito)',
                'Janet Elizondo',
                'Jose Antonio',
                'La Tita',
                'Luis Salazar',
                'Male Jr Martinez',
                'Marifer Martinez',
                'Pato Delgado',
                'Patricia Salazar',
                'Regina Elizondo',
                'Santiago Elizondo',
                'Valvina Elizondo']

families = [('El Tito',
             'La Tita'),
            ('German Sr Martinez',
             'German Jr Martinez',
             'Male Jr Martinez',
             'Marifer Martinez'),
            ('Hugo 2nd (Tio)',
             'Hugo 3rd (Huguito)',
             'Bella Delgado',
             'Ale Delgado',
             'Pato Delgado'),
            ('Janet Elizondo',
             'Jose Antonio',
             'Santiago Elizondo',
             'Valvina Elizondo',
             'Fer Elizondo',
             'Regina Elizondo'),
            ('Patricia Salazar',
             'Luis Salazar',
             'Barbara Salazar')]
